### ISSUE TITLE
Design API for Hook System

### ISSUE THREAD

**Issue by jkrems** [googleinterns/presm#1]
#### Big Open Question

* How to do backtracking of generated file paths?
* What is the API for writing a resource provider? How are they configured?
* What is the API of writing a pre-processor? How are they configured?
* What is the API of writing a post-processor? How are they configured?
* [Future Looking] How could this handle dynamic import?
* Is putting the source paths into standard `package.json` fields viable (with a tool generating a separate `package.json` for publishing)?
* Running the source file vs. the generated file - or both?
  `node --loader=presm ./src/calc_runner.ts` vs. `node --loader=presm ./dist/calc_runner.mjs`

**Comment by julian-londono** [comment]
### Backtracking file paths
Tackling the backtracking of generated file paths (reversibility) I believe a good start is "Require unique basenames to make file-provider enough to get full mapping." as noted in the [exploration here](https://github.com/googleinterns/presm/tree/api-exploration/examples/calc).

#### Pros
- Allows straightforward reverse lookup
(e.g. `dist/_fs/src0/components/calc.mjs` &rarr; `/src0/components/calc.<extension X>`
#### Cons
- Restricts users to unique base files - this presents various degrees of problem but my intuition thinks it won't be too bad

**Comment by jkrems** [comment]
One thing I was trying to play through earlier was also the indexing solution. Assuming that the chain is declarative (none of it needs to run for the chain to be fully known), it should be possible to build a complete index. I think that was one of your original ideas. At most it may need some uncertainty (this transform applies to all coffee and may either create mjs or CJS, so both are added to the index).

**Comment by julian-londono** [comment]
@jkrems this would still require unique base file names correct?

**Comment by jkrems** [comment]
To some degree yes. But not necessarily. E.g. it would allow foo.json and foo.ts in the same directory (at least potentially). Depending on how exactly they get mapped.

**Comment by julian-londono** [comment]
Continuing to think through this formally in the README, @jkrems , a file `foo.mjs` could have come from either `.ts` or `.yaml` in our example.  Does `foo.ts.mjs` sound too clunky to help solve this issue? Is this type of naming what you might have thought as `{calc.ts id}.mjs`?

**Comment by jkrems** [comment]
I think that kind of name could be fine. What I was hoping was to keep the "typical" case clean. Giving everybody weird output filename because some people may have conflicting names would be unfortunate. In the README I used `calc$1.mjs` to resolve the conflict ("if something else took the name, generate a unique derived filename"). But I think the details could be malleable in the future, so I would just start with something that works - and `foo.ts.mjs` definitely works.

**Comment by julian-londono** [comment]
Makes sense, will formalize with `foo.ts.mjs` type of mapping but keep in mind for a future implementation change!

**Comment by julian-londono** [comment]
## API for `resourceProviders` as referenced in [project config](https://github.com/googleinterns/presm/tree/api-exploration/examples/calc#project-configuration)

### Requirements of writing a `resourceProvider` itself:
- Expose which kinds of resource paths it can handle 
    - e.g. the `file` loader can handle `file:///` prefixes
    - e.g. the `https` can handle `https://` prefixes and potentially `http://` prefixes  - depending on config
    - NOTE: a `zip` loader might have to handle a certain suffix as well
        - `.zip`, `.gz`, etc. 
        - Chained resource provider: case where `.zip` is coming from `https`
- Return source of resource (`https` case) or direct local location where other loaders can use/find it (`file` case, potentially `.zip` case)
    - Likely returned as a `Buffer`
    - NOTE: this is where we could explore returning data objects instead of a buffer
        - E.g. `https` loader `get`-ing a `JSON` file from the network should not have to serialize it into a `Buffer` only to have another loader parse the `JSON` object again -  will continue to think through this aspect

### Requirements of including and configuring a `resourceProvider` - in [project config](https://github.com/googleinterns/presm/tree/api-exploration/examples/calc#project-configuration):
- Specify loader
- Specify a list of `base` directories that `presm` will operate on with this loader
         - Could default to `package.json`'s `exports` list
Example:
```js
  "resourceProviders": [
    { "name": "@presm/file", "bases": ["./src"] },
    { "name": "@presm/https", "bases":[ ] }
  ],
```

**Comment by julian-londono** [comment]
## API for `preProcessors` as referenced in [project config](https://github.com/googleinterns/presm/tree/api-exploration/examples/calc#project-configuration)

#### Main role: convert from one format to another format

### Requirements of writing a `preProcessor` itself:
- Expose `sourceExtensionTypes` (from) and `outputExtensionTypes` (to) extension types for file types it can handle and output
    - Both `sourceExtensionTypes` and `outputExtensionTypes` are likely arrays
        - E.g. a `TypeScript` `preProcessor` might convert from [`.ts` , `.tsx`] to [`.mjs`, `.cjs`]
    - NOTE: TBD a uniform formal way to expose these
- Create an appropriate interface to configure this `preProcessor`'s behavior in [project config](https://github.com/googleinterns/presm/tree/api-exploration/examples/calc#project-configuration)
    - See example below &darr; &darr; 

- NOTE: Could also define defaults options
    - For a `TypeScript` `preProcessor`, a default might be to use the project's existing `tsconfig.json`
- Return converted source file(s) complete with a valid extension of `outputExtensionTypes`
- Behavior Note: I do not believe a `preProcessor` should be filtering files based on these extensions, I believe that to be the responsibility of the caller for this loader

### Requirements of including and configuring a resourceProvider - in [project config](https://github.com/googleinterns/presm/tree/api-exploration/examples/calc#project-configuration):
- Specify loader `name`
- Specify `options` (optional)
     - NOTE: this interface should be defined by the `preProcessor` but all configuration options should go under `options`
Example:
```js
          "preProcessors": [
            {
              "name": "@presm/typescript",
              "options": {
                "tsconfigFile": "./tsconfig.json",
              },
            },
            {
              "name": "@presm/json",
            },
          ],
```

**Comment by julian-londono** [comment]
# Migrated future exploration of these issues to PRs:
- [Resource Providers, PR #2 ](https://github.com/googleinterns/presm/pull/2)

- [Pre Processors, PR #3 ](https://github.com/googleinterns/presm/pull/3)
